// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kcal.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const bumpMinValidVersion = `-- name: BumpMinValidVersion :exec
UPDATE sync_metadata
SET min_valid_version = GREATEST(min_valid_version, $2)
WHERE user_id = $1
`

type BumpMinValidVersionParams struct {
	UserID          int64
	MinValidVersion int64
}

func (q *Queries) BumpMinValidVersion(ctx context.Context, arg BumpMinValidVersionParams) error {
	_, err := q.db.ExecContext(ctx, bumpMinValidVersion, arg.UserID, arg.MinValidVersion)
	return err
}

const createKcalEntry = `-- name: CreateKcalEntry :one
INSERT INTO kcal_entries (
    id,
    user_id,
    kcal_delta,
    happened_at,
    client_updated_at,
    server_updated_at,
    deleted_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, kcal_delta, happened_at, client_updated_at, server_updated_at, global_version, deleted_at
`

type CreateKcalEntryParams struct {
	ID              uuid.UUID
	UserID          int64
	KcalDelta       int32
	HappenedAt      time.Time
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
	DeletedAt       sql.NullTime
}

func (q *Queries) CreateKcalEntry(ctx context.Context, arg CreateKcalEntryParams) (KcalEntry, error) {
	row := q.db.QueryRowContext(ctx, createKcalEntry,
		arg.ID,
		arg.UserID,
		arg.KcalDelta,
		arg.HappenedAt,
		arg.ClientUpdatedAt,
		arg.ServerUpdatedAt,
		arg.DeletedAt,
	)
	var i KcalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KcalDelta,
		&i.HappenedAt,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const createKcalTemplateItem = `-- name: CreateKcalTemplateItem :one
INSERT INTO kcal_template_items (
    id,
    user_id,
    kind,
    name,
    amount,
    unit,
    kcal_amount,
    client_updated_at,
    server_updated_at,
    deleted_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, user_id, kind, name, amount, unit, kcal_amount, client_updated_at, server_updated_at, global_version, deleted_at
`

type CreateKcalTemplateItemParams struct {
	ID              uuid.UUID
	UserID          int64
	Kind            KcalTemplateKind
	Name            string
	Amount          string
	Unit            string
	KcalAmount      int32
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
	DeletedAt       sql.NullTime
}

func (q *Queries) CreateKcalTemplateItem(ctx context.Context, arg CreateKcalTemplateItemParams) (KcalTemplateItem, error) {
	row := q.db.QueryRowContext(ctx, createKcalTemplateItem,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.KcalAmount,
		arg.ClientUpdatedAt,
		arg.ServerUpdatedAt,
		arg.DeletedAt,
	)
	var i KcalTemplateItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.KcalAmount,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExpiredEntryTombstones = `-- name: DeleteExpiredEntryTombstones :many
DELETE FROM kcal_entries AS entries
WHERE entries.user_id = $1
  AND entries.deleted_at IS NOT NULL
  AND entries.server_updated_at < $2
RETURNING entries.global_version
`

type DeleteExpiredEntryTombstonesParams struct {
	UserID          int64
	ServerUpdatedAt time.Time
}

func (q *Queries) DeleteExpiredEntryTombstones(ctx context.Context, arg DeleteExpiredEntryTombstonesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredEntryTombstones, arg.UserID, arg.ServerUpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var global_version int64
		if err := rows.Scan(&global_version); err != nil {
			return nil, err
		}
		items = append(items, global_version)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredTemplateTombstones = `-- name: DeleteExpiredTemplateTombstones :many
DELETE FROM kcal_template_items AS template_items
WHERE template_items.user_id = $1
  AND template_items.deleted_at IS NOT NULL
  AND template_items.server_updated_at < $2
RETURNING template_items.global_version
`

type DeleteExpiredTemplateTombstonesParams struct {
	UserID          int64
	ServerUpdatedAt time.Time
}

func (q *Queries) DeleteExpiredTemplateTombstones(ctx context.Context, arg DeleteExpiredTemplateTombstonesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredTemplateTombstones, arg.UserID, arg.ServerUpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var global_version int64
		if err := rows.Scan(&global_version); err != nil {
			return nil, err
		}
		items = append(items, global_version)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteKcalEntry = `-- name: DeleteKcalEntry :one
UPDATE kcal_entries
SET client_updated_at = $3,
    server_updated_at = $4,
    deleted_at = $4,
    global_version = DEFAULT
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, kcal_delta, happened_at, client_updated_at, server_updated_at, global_version, deleted_at
`

type DeleteKcalEntryParams struct {
	ID              uuid.UUID
	UserID          int64
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
}

func (q *Queries) DeleteKcalEntry(ctx context.Context, arg DeleteKcalEntryParams) (KcalEntry, error) {
	row := q.db.QueryRowContext(ctx, deleteKcalEntry,
		arg.ID,
		arg.UserID,
		arg.ClientUpdatedAt,
		arg.ServerUpdatedAt,
	)
	var i KcalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KcalDelta,
		&i.HappenedAt,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const deleteKcalTemplateItem = `-- name: DeleteKcalTemplateItem :one
UPDATE kcal_template_items
SET client_updated_at = $3,
    server_updated_at = $4,
    deleted_at = $4,
    global_version = DEFAULT
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, kind, name, amount, unit, kcal_amount, client_updated_at, server_updated_at, global_version, deleted_at
`

type DeleteKcalTemplateItemParams struct {
	ID              uuid.UUID
	UserID          int64
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
}

func (q *Queries) DeleteKcalTemplateItem(ctx context.Context, arg DeleteKcalTemplateItemParams) (KcalTemplateItem, error) {
	row := q.db.QueryRowContext(ctx, deleteKcalTemplateItem,
		arg.ID,
		arg.UserID,
		arg.ClientUpdatedAt,
		arg.ServerUpdatedAt,
	)
	var i KcalTemplateItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.KcalAmount,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const ensureSyncMetadataRow = `-- name: EnsureSyncMetadataRow :exec
INSERT INTO sync_metadata (
    user_id,
    min_valid_version
) VALUES (
    $1,
    0
)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureSyncMetadataRow(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, ensureSyncMetadataRow, userID)
	return err
}

const getKcalEntryByID = `-- name: GetKcalEntryByID :one
SELECT id, user_id, kcal_delta, happened_at, client_updated_at, server_updated_at, global_version, deleted_at
FROM kcal_entries
WHERE id = $1
  AND user_id = $2
`

type GetKcalEntryByIDParams struct {
	ID     uuid.UUID
	UserID int64
}

func (q *Queries) GetKcalEntryByID(ctx context.Context, arg GetKcalEntryByIDParams) (KcalEntry, error) {
	row := q.db.QueryRowContext(ctx, getKcalEntryByID, arg.ID, arg.UserID)
	var i KcalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KcalDelta,
		&i.HappenedAt,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getKcalEntryForUpdate = `-- name: GetKcalEntryForUpdate :one
SELECT id, user_id, kcal_delta, happened_at, client_updated_at, server_updated_at, global_version, deleted_at
FROM kcal_entries
WHERE id = $1
  AND user_id = $2
FOR UPDATE
`

type GetKcalEntryForUpdateParams struct {
	ID     uuid.UUID
	UserID int64
}

func (q *Queries) GetKcalEntryForUpdate(ctx context.Context, arg GetKcalEntryForUpdateParams) (KcalEntry, error) {
	row := q.db.QueryRowContext(ctx, getKcalEntryForUpdate, arg.ID, arg.UserID)
	var i KcalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KcalDelta,
		&i.HappenedAt,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getKcalTemplateItemByID = `-- name: GetKcalTemplateItemByID :one
SELECT id, user_id, kind, name, amount, unit, kcal_amount, client_updated_at, server_updated_at, global_version, deleted_at
FROM kcal_template_items
WHERE id = $1
  AND user_id = $2
`

type GetKcalTemplateItemByIDParams struct {
	ID     uuid.UUID
	UserID int64
}

func (q *Queries) GetKcalTemplateItemByID(ctx context.Context, arg GetKcalTemplateItemByIDParams) (KcalTemplateItem, error) {
	row := q.db.QueryRowContext(ctx, getKcalTemplateItemByID, arg.ID, arg.UserID)
	var i KcalTemplateItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.KcalAmount,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getKcalTemplateItemForUpdate = `-- name: GetKcalTemplateItemForUpdate :one
SELECT id, user_id, kind, name, amount, unit, kcal_amount, client_updated_at, server_updated_at, global_version, deleted_at
FROM kcal_template_items
WHERE id = $1
  AND user_id = $2
FOR UPDATE
`

type GetKcalTemplateItemForUpdateParams struct {
	ID     uuid.UUID
	UserID int64
}

func (q *Queries) GetKcalTemplateItemForUpdate(ctx context.Context, arg GetKcalTemplateItemForUpdateParams) (KcalTemplateItem, error) {
	row := q.db.QueryRowContext(ctx, getKcalTemplateItemForUpdate, arg.ID, arg.UserID)
	var i KcalTemplateItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.KcalAmount,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getKcalTotalInRange = `-- name: GetKcalTotalInRange :one
SELECT COALESCE(SUM(kcal_delta), 0)::bigint AS total_kcal
FROM kcal_entries
WHERE user_id = $1
  AND deleted_at IS NULL
  AND happened_at >= $2
  AND happened_at < $3
`

type GetKcalTotalInRangeParams struct {
	UserID       int64
	HappenedAt   time.Time
	HappenedAt_2 time.Time
}

func (q *Queries) GetKcalTotalInRange(ctx context.Context, arg GetKcalTotalInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getKcalTotalInRange, arg.UserID, arg.HappenedAt, arg.HappenedAt_2)
	var total_kcal int64
	err := row.Scan(&total_kcal)
	return total_kcal, err
}

const listKcalEntriesInRange = `-- name: ListKcalEntriesInRange :many
SELECT id, user_id, kcal_delta, happened_at, client_updated_at, server_updated_at, global_version, deleted_at
FROM kcal_entries
WHERE user_id = $1
  AND deleted_at IS NULL
  AND happened_at >= $2
  AND happened_at < $3
ORDER BY happened_at DESC, id DESC
`

type ListKcalEntriesInRangeParams struct {
	UserID       int64
	HappenedAt   time.Time
	HappenedAt_2 time.Time
}

func (q *Queries) ListKcalEntriesInRange(ctx context.Context, arg ListKcalEntriesInRangeParams) ([]KcalEntry, error) {
	rows, err := q.db.QueryContext(ctx, listKcalEntriesInRange, arg.UserID, arg.HappenedAt, arg.HappenedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KcalEntry
	for rows.Next() {
		var i KcalEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KcalDelta,
			&i.HappenedAt,
			&i.ClientUpdatedAt,
			&i.ServerUpdatedAt,
			&i.GlobalVersion,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKcalTemplateItemsByKind = `-- name: ListKcalTemplateItemsByKind :many
SELECT id, user_id, kind, name, amount, unit, kcal_amount, client_updated_at, server_updated_at, global_version, deleted_at
FROM kcal_template_items
WHERE user_id = $1
  AND kind = $2
  AND deleted_at IS NULL
ORDER BY name, id
`

type ListKcalTemplateItemsByKindParams struct {
	UserID int64
	Kind   KcalTemplateKind
}

func (q *Queries) ListKcalTemplateItemsByKind(ctx context.Context, arg ListKcalTemplateItemsByKindParams) ([]KcalTemplateItem, error) {
	rows, err := q.db.QueryContext(ctx, listKcalTemplateItemsByKind, arg.UserID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KcalTemplateItem
	for rows.Next() {
		var i KcalTemplateItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.KcalAmount,
			&i.ClientUpdatedAt,
			&i.ServerUpdatedAt,
			&i.GlobalVersion,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRecordsSince = `-- name: ListSyncRecordsSince :many
SELECT entity_table,
       id,
       kind,
       name,
       amount,
       unit,
       kcal_amount,
       kcal_delta,
       happened_at,
       client_updated_at,
       server_updated_at,
       global_version,
       deleted
FROM (
    SELECT 'kcal_template_items'::text AS entity_table,
           id,
           kind::text,
           name,
           amount::text,
           unit,
           kcal_amount,
           NULL::integer AS kcal_delta,
           NULL::timestamptz AS happened_at,
           client_updated_at,
           server_updated_at,
           global_version,
           (deleted_at IS NOT NULL)::boolean AS deleted
    FROM kcal_template_items AS template_items
    WHERE template_items.user_id = $1
      AND template_items.global_version > $2

    UNION ALL

    SELECT 'kcal_entries'::text AS entity_table,
           id,
          ''::text AS kind,
          ''::text AS name,
          ''::text AS amount,
          ''::text AS unit,
          0::integer AS kcal_amount,
           kcal_delta,
           happened_at,
           client_updated_at,
           server_updated_at,
           global_version,
          (deleted_at IS NOT NULL)::boolean AS deleted
    FROM kcal_entries AS entries
    WHERE entries.user_id = $1
      AND entries.global_version > $2
) AS sync_records
ORDER BY global_version, entity_table, id
`

type ListSyncRecordsSinceParams struct {
	UserID        int64
	GlobalVersion int64
}

type ListSyncRecordsSinceRow struct {
	EntityTable     string
	ID              uuid.UUID
	Kind            string
	Name            string
	Amount          string
	Unit            string
	KcalAmount      int32
	KcalDelta       sql.NullInt32
	HappenedAt      sql.NullTime
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
	GlobalVersion   int64
	Deleted         bool
}

func (q *Queries) ListSyncRecordsSince(ctx context.Context, arg ListSyncRecordsSinceParams) ([]ListSyncRecordsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSyncRecordsSince, arg.UserID, arg.GlobalVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncRecordsSinceRow
	for rows.Next() {
		var i ListSyncRecordsSinceRow
		if err := rows.Scan(
			&i.EntityTable,
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.KcalAmount,
			&i.KcalDelta,
			&i.HappenedAt,
			&i.ClientUpdatedAt,
			&i.ServerUpdatedAt,
			&i.GlobalVersion,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncSnapshot = `-- name: ListSyncSnapshot :many
SELECT entity_table,
       id,
       kind,
       name,
       amount,
       unit,
       kcal_amount,
       kcal_delta,
       happened_at,
       client_updated_at,
       server_updated_at,
       global_version,
       deleted
FROM (
    SELECT 'kcal_template_items'::text AS entity_table,
           id,
           kind::text,
           name,
           amount::text,
           unit,
           kcal_amount,
           NULL::integer AS kcal_delta,
           NULL::timestamptz AS happened_at,
           client_updated_at,
           server_updated_at,
           global_version,
           FALSE::boolean AS deleted
    FROM kcal_template_items AS template_items
    WHERE template_items.user_id = $1
      AND template_items.deleted_at IS NULL

    UNION ALL

    SELECT 'kcal_entries'::text AS entity_table,
           id,
          ''::text AS kind,
          ''::text AS name,
          ''::text AS amount,
          ''::text AS unit,
          0::integer AS kcal_amount,
           kcal_delta,
           happened_at,
           client_updated_at,
           server_updated_at,
           global_version,
          FALSE::boolean AS deleted
    FROM kcal_entries AS entries
    WHERE entries.user_id = $1
      AND entries.deleted_at IS NULL
) AS sync_snapshot
ORDER BY server_updated_at DESC, entity_table, id
`

type ListSyncSnapshotRow struct {
	EntityTable     string
	ID              uuid.UUID
	Kind            string
	Name            string
	Amount          string
	Unit            string
	KcalAmount      int32
	KcalDelta       sql.NullInt32
	HappenedAt      sql.NullTime
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
	GlobalVersion   int64
	Deleted         bool
}

func (q *Queries) ListSyncSnapshot(ctx context.Context, userID int64) ([]ListSyncSnapshotRow, error) {
	rows, err := q.db.QueryContext(ctx, listSyncSnapshot, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncSnapshotRow
	for rows.Next() {
		var i ListSyncSnapshotRow
		if err := rows.Scan(
			&i.EntityTable,
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.KcalAmount,
			&i.KcalDelta,
			&i.HappenedAt,
			&i.ClientUpdatedAt,
			&i.ServerUpdatedAt,
			&i.GlobalVersion,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSyncMetadata = `-- name: ReadSyncMetadata :one
SELECT GREATEST(
       COALESCE((SELECT MAX(template_items.global_version) FROM kcal_template_items AS template_items WHERE template_items.user_id = $1), 0),
       COALESCE((SELECT MAX(entries.global_version) FROM kcal_entries AS entries WHERE entries.user_id = $1), 0),
       metadata.min_valid_version
       )::BIGINT AS current_version,
     metadata.min_valid_version
FROM sync_metadata AS metadata
WHERE metadata.user_id = $1
`

type ReadSyncMetadataRow struct {
	CurrentVersion  int64
	MinValidVersion int64
}

func (q *Queries) ReadSyncMetadata(ctx context.Context, userID int64) (ReadSyncMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, readSyncMetadata, userID)
	var i ReadSyncMetadataRow
	err := row.Scan(&i.CurrentVersion, &i.MinValidVersion)
	return i, err
}

const updateKcalEntry = `-- name: UpdateKcalEntry :one
UPDATE kcal_entries
SET kcal_delta = $3,
    happened_at = $4,
    client_updated_at = $5,
    server_updated_at = $6,
    deleted_at = $7,
    global_version = DEFAULT
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, kcal_delta, happened_at, client_updated_at, server_updated_at, global_version, deleted_at
`

type UpdateKcalEntryParams struct {
	ID              uuid.UUID
	UserID          int64
	KcalDelta       int32
	HappenedAt      time.Time
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
	DeletedAt       sql.NullTime
}

func (q *Queries) UpdateKcalEntry(ctx context.Context, arg UpdateKcalEntryParams) (KcalEntry, error) {
	row := q.db.QueryRowContext(ctx, updateKcalEntry,
		arg.ID,
		arg.UserID,
		arg.KcalDelta,
		arg.HappenedAt,
		arg.ClientUpdatedAt,
		arg.ServerUpdatedAt,
		arg.DeletedAt,
	)
	var i KcalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KcalDelta,
		&i.HappenedAt,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const updateKcalTemplateItem = `-- name: UpdateKcalTemplateItem :one
UPDATE kcal_template_items
SET kind = $3,
    name = $4,
    amount = $5,
    unit = $6,
    kcal_amount = $7,
    client_updated_at = $8,
    server_updated_at = $9,
    deleted_at = $10,
    global_version = DEFAULT
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, kind, name, amount, unit, kcal_amount, client_updated_at, server_updated_at, global_version, deleted_at
`

type UpdateKcalTemplateItemParams struct {
	ID              uuid.UUID
	UserID          int64
	Kind            KcalTemplateKind
	Name            string
	Amount          string
	Unit            string
	KcalAmount      int32
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
	DeletedAt       sql.NullTime
}

func (q *Queries) UpdateKcalTemplateItem(ctx context.Context, arg UpdateKcalTemplateItemParams) (KcalTemplateItem, error) {
	row := q.db.QueryRowContext(ctx, updateKcalTemplateItem,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.KcalAmount,
		arg.ClientUpdatedAt,
		arg.ServerUpdatedAt,
		arg.DeletedAt,
	)
	var i KcalTemplateItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.KcalAmount,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
		&i.GlobalVersion,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDeviceSyncState = `-- name: UpsertDeviceSyncState :exec
INSERT INTO device_sync_state (
    user_id,
    device_id,
    last_sync_version
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (user_id, device_id) DO UPDATE
SET last_sync_version = EXCLUDED.last_sync_version
`

type UpsertDeviceSyncStateParams struct {
	UserID          int64
	DeviceID        uuid.UUID
	LastSyncVersion int64
}

func (q *Queries) UpsertDeviceSyncState(ctx context.Context, arg UpsertDeviceSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeviceSyncState, arg.UserID, arg.DeviceID, arg.LastSyncVersion)
	return err
}
