// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"kcal-counter/internal/store/dbtype"

	"github.com/google/uuid"
)

type KcalTemplateKind string

const (
	KcalTemplateKindFood     KcalTemplateKind = "food"
	KcalTemplateKindActivity KcalTemplateKind = "activity"
)

func (e *KcalTemplateKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KcalTemplateKind(s)
	case string:
		*e = KcalTemplateKind(s)
	default:
		return fmt.Errorf("unsupported scan type for KcalTemplateKind: %T", src)
	}
	return nil
}

type NullKcalTemplateKind struct {
	KcalTemplateKind KcalTemplateKind
	Valid            bool // Valid is true if KcalTemplateKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKcalTemplateKind) Scan(value interface{}) error {
	if value == nil {
		ns.KcalTemplateKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KcalTemplateKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKcalTemplateKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KcalTemplateKind), nil
}

type DeviceSyncState struct {
	UserID          int64
	DeviceID        uuid.UUID
	LastSyncVersion int64
}

type KcalEntry struct {
	ID              uuid.UUID
	UserID          int64
	KcalDelta       int32
	HappenedAt      time.Time
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
	GlobalVersion   int64
	DeletedAt       sql.NullTime
}

type KcalTemplateItem struct {
	ID              uuid.UUID
	UserID          int64
	Kind            KcalTemplateKind
	Name            string
	Amount          string
	Unit            string
	KcalAmount      int32
	ClientUpdatedAt time.Time
	ServerUpdatedAt time.Time
	GlobalVersion   int64
	DeletedAt       sql.NullTime
}

type PasskeyCredential struct {
	ID                  int64
	UserID              int64
	CredentialID        []byte
	CredentialPublicKey []byte
	AttestationType     string
	Aaguid              uuid.NullUUID
	SignCount           int64
	CloneWarning        bool
	Transports          []string
	CredentialData      dbtype.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Role struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type ScheduledJob struct {
	ID            int64
	Name          string
	LastRunAt     sql.NullTime
	LastSuccessAt sql.NullTime
	LastError     sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type SyncMetadatum struct {
	UserID          int64
	MinValidVersion int64
}

type User struct {
	ID               int64
	WebauthnUserID   []byte
	LastLoginAt      sql.NullTime
	LastSeenAt       sql.NullTime
	IsActive         bool
	DisabledReason   sql.NullString
	DisabledAt       sql.NullTime
	FailedLoginCount int32
	LockedUntil      sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type UserRole struct {
	UserID    int64
	RoleID    int64
	CreatedAt time.Time
}
