// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package sqlc

import (
	"context"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (
    user_id,
    role_id
) VALUES (
    $1,
    $2
)
ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, addUserRole, arg.UserID, arg.RoleID)
	return err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at
FROM roles
WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listUserRoleNames = `-- name: ListUserRoleNames :many
SELECT roles.name
FROM roles
JOIN user_roles ON user_roles.role_id = roles.id
WHERE user_roles.user_id = $1
ORDER BY roles.name
`

func (q *Queries) ListUserRoleNames(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoleNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
