// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users
(
  webauthn_user_id
)
VALUES ($1)
RETURNING id, webauthn_user_id, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, webauthnUserID []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, webauthnUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WebauthnUserID,
		&i.LastLoginAt,
		&i.LastSeenAt,
		&i.IsActive,
		&i.DisabledReason,
		&i.DisabledAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableInactiveUsers = `-- name: DisableInactiveUsers :many
UPDATE users
SET is_active = FALSE,
    disabled_reason = 'inactivity',
    disabled_at = NOW()
WHERE is_active = TRUE
  AND COALESCE(last_login_at, created_at) < $1
RETURNING id, webauthn_user_id, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at
`

func (q *Queries) DisableInactiveUsers(ctx context.Context, lastLoginAt sql.NullTime) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, disableInactiveUsers, lastLoginAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.WebauthnUserID,
			&i.LastLoginAt,
			&i.LastSeenAt,
			&i.IsActive,
			&i.DisabledReason,
			&i.DisabledAt,
			&i.FailedLoginCount,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, webauthn_user_id, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WebauthnUserID,
		&i.LastLoginAt,
		&i.LastSeenAt,
		&i.IsActive,
		&i.DisabledReason,
		&i.DisabledAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    last_seen_at = NOW(),
    failed_login_count = 0,
    locked_until = NULL
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}
